apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apache
  labels:
    name:  web-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name:  my-name
  template:
    metadata:
      labels:
        name:  my-name
    spec:
      containers:
      - image:  httpd
        name:  apache
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE
        ports:
        - containerPort:  80
          name:  http
        volumeMounts:
        - mountPath: /data
          name: data
        resources: {}
      volumes:
        - name: data
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name:  apache
spec:
  selector:
    name:  my-name
  type:   NodePort
  ports:
  - name:  web
    port:  80
    targetPort:  http

