apiVersion: apps/v1
kind: Deployment #StatefulSet
metadata:
  name:  python-app
  labels:
    name:  python-app
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name:  python-app
  template:
    metadata:
      labels:
        name:  python-app
    spec:
      containers:
      - image:  kontinu/python-app:v1.0
        imagePullPolicy: IfNotPresent
        name:  python-app
        resources: {}
        env:
        - name:  FOO
          value:  "Hello from GitOps - new msg "
        ports:
        - containerPort:  8080
          name:  http
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}


