apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front
  template:
    metadata:
      labels:
        name: front
    spec:
      containers:
      - name: front
        image: kontinu/python-expert:v1.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
        env:
        - name: NEXT_URL
          value: http://middle/api
        - name: FOO
          value: Hello from K8s
        resources: {}

---
kind: Service
apiVersion: v1
metadata:
  name:  front
spec:
  selector:
    name: front
  type: LoadBalancer
  ports:
  - name:  web
    port:  80
    targetPort:  http


